---
title: WanderVogel
baseURL: "/"
params:
  color_scheme: light
  accent_color: violet
  header:
    title: ''
    has_nav: true
    logo_img: "/images/WanderVogel.svg"
  footer:
    content: Powered by Me!
    links:
    - text: Made with Stackbit
      url: https://www.stackbit.com
      new_window: true
    has_social: true
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
