---
title: WanderVogel
baseURL: "/"
params:
  color_scheme: light
  accent_color: violet
  header:
    title: ''
    has_nav: true
    logo_img: "/images/logo2.png"
  footer:
    content: Powered by Me!
    links:
    - text: Made on Hugo
      url: https://www.gohugo.io
      new_window: true
    - text: Managed on Forestry.io
      url: https://app.forestry.io/
      new_window: true
    has_social: true
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
